# Generated by Django 2.0.6 on 2018-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
